### ISSUE TITLE
Add support for bitwise operations

### ISSUE THREAD

**Issue by Petermo** [kahanu/System.Linq.Dynamic#16]
Just encountered some issues where I really wanted to use bitwise operations (as a somewhat generic approach to a Enum its HasFlag).
Am I overlooking something obvious? Regardless, I have started to work on getting bitwise logic in there anyway and will create a PR when I feel it is useable. (https://github.com/Petermo/System.Linq.Dynamic)

However, I was wondering what the original reason was for allowing an ampersand as concatenation operator.

**Comment by kahanu** [comment]
@Petermo - you would have to ask the Microsoft developers who built the framework that question.  I'm not associated with Microsoft, I just made their framework available here so I could also make it available on NuGet.  I know this wasn't the answer you were looking for, but this is the original code by Microsoft (with some other pull request merges), but I'm not the architect.  Sorry.

**Comment by Petermo** [comment]
Yeah, I knew that and that is no problem at all. But I was basically hoping you (or someone else) would happen to know. 
I'm currently fearing that it is in there just because that would be the expected behaviour for  VB developers (and being a part of some code samples for both C# and VB...), ah well; speculation :). 
Other question, do you (or anybody else that reads this)  think side effects might occur or would dropping the support be a dealbreaker for getting the changes merged back in?

**Comment by kahanu** [comment]
@Petermo - I'm not  following your last question about side effects and merging back in.  What do you mean here?

**Comment by Petermo** [comment]
Well, since I do use it a lot, but only limited I was wondering what unwanted side effects could surface after removing the concatenation feature (using an &). 
And, since I remove a feature, if you would still feel comfortable accepting a pull request. I do prefer it if it would all end up in the same location.

**Comment by Petermo** [comment]
BTW, I also found a similar project on codeplex maybe I'll browse around over there to see if I can find an answer to my 'why is it originally created like this' question.

**Comment by kahanu** [comment]
@Petermo - I wouldn't remove it in case some developer is using it and wants to upgrade to the latest. If it is working for them, it would break their application.  It could be marked as Deprecated or something if a good work around is implemented.

**Comment by Petermo** [comment]
@kahanu, ok I've changed it a bit so backwards compatibility is ensured and it can be seen as nothing but an addition. I've also created a PR for it now.
