### ISSUE TITLE
ParseStringLiteral fails for strings @"'this is my string with spaces and single quoted'"

### ISSUE THREAD

**Issue by hidegh** [kahanu/System.Linq.Dynamic#20]
**What's the purpose of this function.**
1. First it strips the quote from the beginning and end of the token.text (without checking if it's good encoded)
2. Then in the WHILE part it simply replaces double single quotes with a single single quote (assumes that there's a double quote, does not check it)
3. **Then if our qoute is a single quote, then an error is raised, since s == token.text and must not be length of 1 !!!**

After replacing ' to " everything is OK.
**What i don't understand, why when having single quote ' we have to have text with length 1 char.** Since single quote is often used as marking text boundaries. So why assume that only a char is will be single quoted?

``` code
                Expression ParseStringLiteral()
		{
			ValidateToken(TokenId.StringLiteral);
			char quote = token.text[0];
			string s = token.text.Substring(1, token.text.Length - 2);
			int start = 0;
			while (true)
			{
				int i = s.IndexOf(quote, start);
				if (i < 0) break;
				s = s.Remove(i, 1);
				start = i + 1;
			}
			if (quote == '\'')
			{
				if (s.Length != 1)
					throw ParseError(Res.InvalidCharacterLiteral);
				NextToken();
				return CreateLiteral(s[0], s);
			}
			NextToken();
			return CreateLiteral(s, s);
		}
```

**Comment by kahanu** [comment]
@hidegh - you should probably ask this question on StackOverflow.  I didn't author this, I'm simply providing a way for it to be available, and used in NuGet.  Sorry.

**Comment by ryanvgates** [comment]
@hidegh did you ever ask this question on StackOverflow? If so can you add a link to it?

**Comment by hidegh** [comment]
i don't think so. i replaced the 'string' with "string" and that did the
trick.
there's a logical explanation why they interpret '' as char - they stick to
C#/.NET notation.

**Comment by ryanvgates** [comment]
@hidegh do you mind if I close this issue then?

**Comment by hidegh** [comment]
it's o.k. to close it, with the info I provided you yesterday.
thanx.

**Comment by ryanvgates** [comment]
@hidegh Per your comment, I'm closing this issue.
