### ISSUE TITLE
Orderby Issue

### ISSUE THREAD

**Issue by schzade** [kahanu/System.Linq.Dynamic#23]
public class BoatType
{
      public BoatType(){
             this.BoatTypeTranslation = new HashSet<BoatTypeTranslation>();
      }
      public int Id {get;set;}
      public string Code {get;set;}
      
      public ICollection<BoatTypeTranslation > BoatTypeTranslation {get;set;}
}

public class BoatTypeTranslation
{
      public int Id{get;set}
      public int BoatTypeId{get;set}
      public string Name {get;set;}
      pulic int LanguageId {get;set;}
}

here is my entity.

I want to sort boattype as follow

context.BoatType.AsEnumerable().OrderBy("BoatTypeTranslation.FirstOrDefault(LanguageId == 1).Name")

I want to access inner child collection from the BoatType entity.

Is it possible?

**Comment by kahanu** [comment]
@schzade - you would probably get better responses from stackoverflow.com on this.  I have just made this library available via NuGet, but I am not the author.
