### ISSUE TITLE
ParseException shouldn't override ToString()

### ISSUE THREAD

**Issue by ryanvgates** [kahanu/System.Linq.Dynamic#24]
In the ParseException class, the ToString() method is [overriden](https://github.com/kahanu/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs#L573-L576).

I understand that a simpler message is trying to be achieved, but this creates real problems if I want to catch the exception further up in the call stack. The [System.Exception.ToString()](https://msdn.microsoft.com/en-us/library/system.exception.tostring(v=vs.110).aspx) follows the below standard.

> The default implementation of ToString obtains the name of the class that threw the current exception, the message, the result of calling ToString on the inner exception, and the result of calling Environment.StackTrace. If any of these members is null, its value is not included in the returned string.

I would argue that the code should append the standard information, or it should be a separate method leaving the  [System.Exception.ToString()](https://msdn.microsoft.com/en-us/library/system.exception.tostring(v=vs.110).aspx) method intact.

**Comment by ryanvgates** [comment]
I understand that you are not maintaining this package. If I provide a pull request, is this something that you would be interested in merging in?

P.S. I would be interested in helping maintain this package if you are interested in.

**Comment by kahanu** [comment]
@ryanvgates - yes, if you are interested in helping maintain this package, I'd like that.  My time is limited and when I can't reliably test pull requests, then they can't and shouldn't just be added hoping that the code works.  I've never added a contributor.  I guess I just add your username?  :^)

**Comment by ryanvgates** [comment]
@kahanu yes, if you go to the repository => Settings => Collaborators => add my username => Click Add Collaborator

**Comment by kahanu** [comment]
@ryanvgates - I think I did it.  Can you check?

**Comment by ryanvgates** [comment]
@kahanu  I think so. I now see the button to merge the pull request and it says "Collaborator" next to the edit pencil icon. Thank you.

**Comment by kahanu** [comment]
@ryanvgates - no thank you for being a collaborator.

**Comment by ryanvgates** [comment]
@kahanu if you think the pull request looks good I'll merge it in. I promise not to ask you about each and every one. In this case since, I'd like another set of eyes on the changes since it's my pull request, and I may be somewhat biased.

**Comment by ryanvgates** [comment]
Closing this since making the change would impact existing users that would upgrade.
