### ISSUE TITLE
Issue with null check

### ISSUE THREAD

**Issue by ggrote** [kahanu/System.Linq.Dynamic#25]
I've got the following entity:
```
public class BasRegion {
public String Name {get;set;}
...
}
```
and I want to filter them by Name, but some of them have the Name property set to null.
The where query:
```
string query = "Region.Name != null && Region.Name.ToLower().StartsWith("we");
```
generates the following statement:
```
.Where(Param_0 => ((Convert(Param_0.Region.Name) != null) AndAlso Param_0.Region.Name.ToLower().StartsWith(\"we\")))"
```
which leads to a NullReferenceException
```
   bei lambda_method(Closure , xxxxxxx)
   bei System.Linq.Enumerable.<>c__DisplayClass0`1.<CombinePredicates>b__1(TSource x)
   bei System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   bei lambda_method(Closure )
   bei System.Linq.EnumerableExecutor`1.Execute()
   bei System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   bei System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```

**Comment by ryanvgates** [comment]
@kahanu I haven't tried to reproduce this issue yet, but one thing that I think would help would be to have unit tests to reproduce issues and verify that they are fixed. What do you think?

**Comment by kahanu** [comment]
I think that's a good idea.  Can you do that?  Unfortunately I'm crushed on a large project right now.

**Comment by ryanvgates** [comment]
@kahanu I will move forward with that then. Unfortunately I'm in a similar position so it may be a gradual process.

**Comment by ggrote** [comment]
I'm sorry, but I'm too stupid. 
Didn't test it right now, but the problem will be that I only check if Region.Name will be null, which is a property on a navigation property, so I also need to check if Region is null. Sometimes it's that easy... :)
