### ISSUE TITLE
Include ?? operator

### ISSUE THREAD

**Issue by DelvisR** [kahanu/System.Linq.Dynamic#27]
Using Linq is very easy to say: Table.Select (s => new {Res s.Field1 ?? = ""});

Similarly it would be perfect to use with Dynamic Linq: Table.Select ("new (Field1 ?? \" \ "as Res)");

They could use iif or ? : operators, But sometimes a very large string is generated.

It could be added?

Thank you.

**Comment by ryanvgates** [comment]
@DelvisR Can you provide some example code for this? It would help provide a better context for this enhancement.

**Comment by DelvisR** [comment]
On many occasions I need to make dynamic queries where one of the fields can be null response and need instead of zero returns an empty string.

In a traditional Linq query would be:

var dc = new DataClasses1DataContext();

var d = dc.ENTArea
           .Select(s => new { Area = s.Description, 
					Account = s.ENTAreaType.INVProductAreaType.First(q => q.ProductTypeID == s.AreaID).AccountCost.Account ?? string.Empty
					});

Using the supplied library I can say:

var d = dc.ENTArea
			.Select("new (Description as Area, iif(ENTAreaType.INVProductAreaType.First(ProductTypeId = ~.AreaId).AccountCost.Account = null,string.Empty,ENTAreaType.INVProductAreaType.First(ProductTypeId = ~.AreaId).AccountCost.Account) as Account)");

But an optimized way would be:

var d = dc.ENTArea
			.Select("new (Description as Area, (ENTAreaType.INVProductAreaType.First(ProductTypeId = ~.AreaId).AccountCost.Account ?? string.Empty) as Account)");			

That's really what I'm asked to do. if no other way I would appreciate your help.

Greetings and thanks for your interest,

Delvis

**Comment by ryanvgates** [comment]
@DelvisR are you referring to the [?? operator](https://msdn.microsoft.com/en-us/library/ms173224.aspx) or the [?: operator](https://msdn.microsoft.com/en-us/library/ty67wk28.aspx)?

**Comment by DelvisR** [comment]
?? operator

**Comment by ryanvgates** [comment]
@DelvisR can you please provide a pull request that includes the changes you are proposing and unit tests?

**Comment by DelvisR** [comment]
If there is a class "Class 1" with a "Field1" field that can be null and you want if its value is null return an empty string, then we can say:

var result = dc.Class1.Select ("new (iif (Field1 = null, string.Empty, Field1) as Value)");

I propose to incorporate the operator "??" in order to remove the operator "iif":

var result = dc.Class1.Select ("new ((Field1 ?? string.Empty) as Value)");

Cheers,

Delvis

**Comment by ryanvgates** [comment]
@DelvisR I understand the change that you are proposing and I can certainly see that it would be beneficial. @kahanu and myself don't have time to add new features to the repository ourselves right now, so if you want to see these changes made, you will need to provide a pull request that includes unit tests.

**Comment by ryanvgates** [comment]
@DelvisR I'm going to close this for now. When you have a pull request ready, please re-open it.
