### ISSUE TITLE
Parsing of literals should use invariant culture

### ISSUE THREAD

**Issue by glopesdev** [kahanu/System.Linq.Dynamic#29]
First of all, thanks for taking the initiative to improve the original dynamic LINQ!
One of the issues I always had with the original library is that it used the default Parse methods without passing in InvariantCulture.

This means that numeric strings may actually parse or not depending on the user's environment. This becomes more confusing because for some cultures, decimal places may be confused with other lexer tokens and so on. Code should always be parsed with InvariantCulture anyway!

**Comment by ryanvgates** [comment]
@glopesdev No problem. I know I've benefited a lot from the open source/online community and I try to give back when I can.

I believe that tryparse will use the current culture if none is specified. The issue arises when you are running under one culture but want to deal with another culture's strings. Is this the correct scenario to reproduce the issue?

**Comment by glopesdev** [comment]
You are correct that ```TryParse``` uses the current culture if none is specified. However, that is exactly what you ***don't*** want in a programming language or script, because it changes your lexer (i.e. you have parser ambiguity because new tokens are introduced in unexpected places).

A simple example.

The script ```Math.Sin(it / 1.0)``` fails to compile in a Portuguese-language system. Why? Because in Portuguese the decimal separator is a comma (**,**) so you would actually have to write ```Math.Sin(it / 1,0)```. However, this now also fails to compile because unfortunately the lexer interprets the comma (,) as an argument list separator, so you're actually now calling a putative function ```Math.Sin``` with two arguments, which actually doesn't exist.

The result: your script breaks and you are stuck in a loop that has no resolution. I can understand how this can easily go unnoticed in countries where the numerical parsing rules match the invariant culture, but the problem is quite glaring once you are exposed to it.

My point is that culture-dependency has no place in code scripts. All numeric literals should be parsed using invariant culture to guarantee the dynamic scripts do not break, no matter the culture where they are run.

Does this make sense? Sorry if I was not clear before, but this issue has nothing to do with cross-culture manipulations, this happens even when the whole system has a single culture. In fact, the problem happens *because* of that.
