### ISSUE TITLE
Calling instance methods does not work unless the type is a predefined type

### ISSUE THREAD

**Issue by glopesdev** [kahanu/System.Linq.Dynamic#31]
This is also another feature that I never understood. There is an explicit check in ```ParseMemberAccess``` that blocks calling any methods if the class is not part of the predefined types (i.e. int, float, Math, etc).

This makes no sense, because it means I can call ```ToString``` if the input is a number, but not if the input is a ```Point```.

I say this check should simply be removed.

**Comment by ryanvgates** [comment]
@glopesdev Can you provide an example in code to help me understand the context better?

**Comment by glopesdev** [comment]
Sure. Here it is:

```csharp
// This line runs with no problems, ReturnType is "string"
var exprValid = DynamicExpression.ParseLambda(typeof(int), null, "it.ToString()");
Console.WriteLine(exprValid.ReturnType);

// This line throws a ParseException saying "Methods on type 'Type' are not accessible"
var exprInvalid = DynamicExpression.ParseLambda(typeof(Type), null, "it.ToString()");
Console.WriteLine(exprValid.ReturnType);
```

I would say the script ```it.ToString()``` should parse no matter what the type. **ToString** is a valid instance method on any object instance. In fact, any method that is available in the particular type should be available to be called.

There is certainly no limitation on the reflection side of things. In fact, all code is already in-place to validate if the method call is valid (i.e. if it has the right number of arguments, if the types match, etc). However, for some reason the initial developer of Dynamic LINQ decided that an additional "filter" was needed that says only methods that were declared by predefined types are allowed.

My claim is that this decision makes no sense no matter how you look at it. All available instance methods should be available to be called if the method exists and has a compatible signature (which is already being checked).

That's why my solution was simply to remove the check. Do you see any reason why this should not be done? (Btw, this is a backwards-compatible change, nothing will break, simply more scripts will now work).

**Comment by jprimke** [comment]
Hello 

This issue occurs again, 
![image](https://user-images.githubusercontent.com/1974732/37790713-9a1b3ac8-2e07-11e8-94e9-c11699d5f2e4.png)

VS 2017 15.6.3 with .net core SDK 2.1.200-preview-007474

Could you explain why?

Thanks in advance.

Joerg

**Comment by ryanvgates** [comment]
@jprimke I apologize for not getting back to you sooner, but can you create a new issue for this with reproduction steps?
