### ISSUE TITLE
No unit tests

### ISSUE THREAD

**Issue by ryanvgates** [kahanu/System.Linq.Dynamic#33]
I know we discussed adding unit tests, but I had some questions on the specifics of that.

1. What framework should be used (MSTest, NUnit, something else)?
2. How about calling the project System.Linq.Dynamic.Test?

**Comment by kahanu** [comment]
@ryanvgates - I think since it's a .Net assembly, MSTest should be fine, and the project name sounds perfect.

**Comment by ryanvgates** [comment]
@kahanu Let me know if the pull request looks good and I will merge it in.

**Comment by kahanu** [comment]
@ryanvgates Yes, it looks good.  Go ahead and merge.

**Comment by ryanvgates** [comment]
Closing after merging in the pull request.
