### ISSUE TITLE
Readme clean up

### ISSUE THREAD

**Issue by ryanvgates** [kahanu/System.Linq.Dynamic#36]
The [main readme](https://github.com/kahanu/System.Linq.Dynamic/blob/master/README.markdown) should include a link to the nuget repository and have install-package System.Linq.Dynamic formatted like below.

> install-package System.Linq.Dynamic

This will make it easier to copy and paste.

**Comment by kahanu** [comment]
@ryanvgates I do have that in the readme file.  It's not a link, but you can copy and paste from it.  What am I missing?

**Comment by ryanvgates** [comment]
I was going to add the link to the nuget repository https://www.nuget.org/packages/System.Linq.Dynamic/ like the below.

I've also created [a NuGet package](https://www.nuget.org/packages/System.Linq.Dynamic/) so it's easy to import into your Visual Studio projects.

Regarding the styling for  the nuget command I was thinking of something like the below.

```
install-package System.Linq.Dynamic
```

I stole that idea from the [FluentValidation Readme](https://github.com/JeremySkinner/FluentValidation).

**Comment by kahanu** [comment]
@ryanvgates I'm not sure I understand what you mean by "styling" of the nuget command.  :(  This NuGet package is already created and has been used many times.  I can add you to my NuGet repository so you can manage updates for System.Linq.Dynamic.  Do you have a NuGet username?  If so I'll add it to my package.

**Comment by ryanvgates** [comment]
@kahanu I mean on the readme itself not the nuget package.

Here's what it looks like now.

install-package System.Linq.Dynamic

I think it would be better if it looked like this.

```
install-package System.Linq.Dynamic
```

**Comment by kahanu** [comment]
@ryanvgates ah, I see.  Yep, you can do that.  :)

**Comment by ryanvgates** [comment]
Closing this after merging in the pull request.

**Comment by ryanvgates** [comment]
@kahanu to answer your question. My nuget username is ryanvgates.
