### ISSUE TITLE
Release Cycle/Nuget Release

### ISSUE THREAD

**Issue by ryanvgates** [kahanu/System.Linq.Dynamic#39]
@kahanu Issues #29 and #31 have been resolved and merged. What is the release cycle for nuget packages? How often do you typically push a new nuget package?

**Comment by glopesdev** [comment]
Judging from the package release history in the [NuGet package website](https://www.nuget.org/packages/System.Linq.Dynamic/) there was one release in 2011 with the first version and then 3 releases in 2014.

It looks like releases might have been change-driven rather than put out at regular intervals, but there is no reported release notes so it's hard to tell what changed.

**Comment by ryanvgates** [comment]
@glopesdev Thanks for looking that up. That's a good point about release notes. It would be helpful even if it was just a list of github issues that were resolved and included.

**Comment by glopesdev** [comment]
@ryanvgates You can release notes to the NuGet package by adding a <releaseNotes> XML element to the [nuspec file](https://github.com/kahanu/System.Linq.Dynamic/blob/master/NuGet/System.Linq.Dynamic.nuspec) (see [here](https://docs.nuget.org/create/nuspec-reference)).

I guess to push a new version of the NuGet package we would need either @kahanu to do it or a shared ownership of the package to be transferred to you so it is possible to do it independently.

@ryanvgates Do I understand correctly that you are now the active maintainer of this project? If so, then it probably makes sense for you to have permissions to also push out NuGet packages.

**Comment by ryanvgates** [comment]
@glopesdev @kahanu and I are maintaining the project. However @kahanu has been pressed for time recently and I've been doing what I can. I do see your point about having permissions to push out NuGet packages. I will work with @kahanu  on that.

**Comment by ryanvgates** [comment]
@glopesdev do you have an example of including release notes in the NuGet package? I looked at the reference but I am still not seeing exactly how it might be done.

**Comment by glopesdev** [comment]
@ryanvgates sure, you can find a simple example of the usage of release notes in [this SO question](http://stackoverflow.com/questions/30612105/show-nuget-package-release-notes).

**Comment by ryanvgates** [comment]
@glopesdev thank you for the references. I think that I understand what you mean now. I asked @kahanu for permissions to the nuget package. I'll let you know when I hear anything.

**Comment by ryanvgates** [comment]
The version in Nuget has been updated to 1.0.5

**Comment by glopesdev** [comment]
That's great to hear, right on time for my release cycle as well!
Thanks!

**Comment by ryanvgates** [comment]
@glopesdev No problem. Thank you for the PR's and keeping this library going.

**Comment by glopesdev** [comment]
@ryanvgates I've just tested the new NuGet package and the fix for issue #31 does not seem to have been included in the build for some reason. A quick look at the binary at reflection reveals that the code for ParseMemberAccess does not match the most recent master.

Is it possible that for some reason the NuGet build was done on an out-of-date branch?

Thanks!

**Comment by ryanvgates** [comment]
@glopesdev sorry about that. It is possible. I will take a look at it myself and then upload a new version to nuget. It probably won't happen until Monday though.

**Comment by ryanvgates** [comment]
@glopesdev I just uploaded a new version 1.0.6 of the nuget package. Please let me know if that works for you.

**Comment by glopesdev** [comment]
@ryanvgates Yes, this does work and I've checked that both fixes seem to be in place. Thanks for the help!

**Comment by ryanvgates** [comment]
@glopesdev No problem.
