### ISSUE TITLE
Can you add functionality to add Property Attributes?

### ISSUE THREAD

**Issue by EmilNachev** [kahanu/System.Linq.Dynamic#41]
public class DynamicProperty
{
...
public Attributes[] Attributes{get;set;} // <- assigned from constructor
...
}

...
PropertyBuilder pb = tb.DefineProperty(dp.Name, PropertyAttributes.HasDefault, dp.Type, null);
change to:
PropertyBuilder pb = tb.DefineProperty(dp.Name, dp.Attributes, dp.Type, null);

Example:
.Select("new (CustomerFromDB as Customer[Display(Name="Good Customer")] )")

I think this will be a good feature.

**Comment by ryanvgates** [comment]
@EmilNachev can you please provide a pull request that includes the changes you are proposing and unit tests?

**Comment by EmilNachev** [comment]
I'm not familiar with the code and I can't make it. I just made a proposal to add attributes for anonymous class and properties.

**Comment by ryanvgates** [comment]
@EmilNachev Okay. @kahanu nor myself has the bandwidth to add features right now so it may just stay a proposal for now.

**Comment by ryanvgates** [comment]
I'm going to close this now since no pull requests have been submitted and no one has the bandwidth to pick it up.
