### ISSUE TITLE
Add a ParseLambda overload to allow specifying the delegate type

### ISSUE THREAD

**Issue by glopesdev** [kahanu/System.Linq.Dynamic#42]
This would allow using `ParseLambda` to create `Action<>` delegates, instead of just `Func<,>` delegates.

Proposed syntax and implementation:
```c#
public static LambdaExpression ParseLambda(Type delegateType, ParameterExpression[] parameters, Type resultType, string expression, params object[] values)
{
    ExpressionParser parser = new ExpressionParser(parameters, expression, values);
    return Expression.Lambda(delegateType, parser.Parse(resultType), parameters);
}
```

**Comment by ryanvgates** [comment]
Can you provide an example of how consuming code would use this to give me some more context?

**Comment by glopesdev** [comment]
Sure, this would be similar to what you already do with `Expression.Lambda`:
```csharp
var lambda = Expression.Lambda(
    typeof(EventHandler),
    Expression.Empty(),
    Expression.Parameter(typeof(object), "sender"),
    Expression.Parameter(typeof(EventArgs), "e"));
var handler = lambda.Compile();
Console.WriteLine(handler.GetType());
```
This basically compiles an `EventHandler` delegate from the corresponding expression tree which takes the two parameters `sender` and `e` and does nothing. You can see the form if you inspect the expression tree in Visual Studio, which should show you: `{(sender, e) => default(Void)}`

If this overload was in place, you could do the same thing with `DynamicExpression`:
```csharp
var lambda = DynamicExpression.ParseLambda(
    typeof(EventHandler),
    new[] { Expression.Parameter(typeof(object), "sender"), Expression.Parameter(typeof(EventArgs), "e") },
    null,
    "Console.WriteLine(e)");
var handler = lambda.Compile();
Console.WriteLine(handler.GetType());
```
Which would produce in this example an `EventHandler` that prints the event to the console. The interface would still not be 100% consistent with `Expression.Lambda`, but this is unfortunately because of past design choices for `System.Linq.Dynamic`.

Anyway, if #44 is accepted then this is actually irrelevant for my use case, since I was after generating `Action<T>` delegates which is already taken care of automatically by `Expression.Lambda`. It would be nice to have though and it is mostly for free. I will try to submit the pull request soon.
