### ISSUE TITLE
Add a Parse overload to allow specifying the delegate type

### ISSUE THREAD

**Issue by glopesdev** [kahanu/System.Linq.Dynamic#43]
This would allow the `Parse` method to provide the full power of `ExpressionParser`. For some reason the original constructor interface was not fully exposed through this method. The current interface is also inconsistent with the `ParseLambda` overloads, which **_do_** expose this interface.

Proposed interface and implementation:
```c#
public static Expression Parse(ParameterExpression[] parameters, Type resultType, string expression, params object[] values)
{
    ExpressionParser parser = new ExpressionParser(parameters, expression, values);
    return parser.Parse(resultType);
}
```

**Comment by ryanvgates** [comment]
I can see what you mean here. Can you submit a pull request with unit tests and reference this issue?
