### ISSUE TITLE
Consider relaxing ExpressionParser validation of method call return type

### ISSUE THREAD

**Issue by glopesdev** [kahanu/System.Linq.Dynamic#44]
Currently `ExpressionParser` disallows method calls that return `void`. There is really no reason to do this, and it prevents `ExpressionParser` from trivially supporting the parsing of `Action<>` delegates.

The final `Expression.Lambda` call would already throw in cases where the method is not compatible with the specified delegate type.

Also, the current guard throws a `ParseException`, which is not strictly true: parsing is fine, the semantic model only fails to bind when the final `Lambda` constructor is called. Semantic binding should be left for `Expression` calls, or at most the guard should be moved to check only the default `ParseLambda` overloads.

**Proposed fix:**
Remove the following 3 lines starting at https://github.com/kahanu/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs#L1445
```c#
                        if (method.ReturnType == typeof(void))
                            throw ParseError(errorPos, Res.MethodIsVoid,
                                id, GetTypeName(method.DeclaringType));
```

**Comment by ryanvgates** [comment]
Where is the code for this? 

> Currently ExpressionParser disallows method calls that return void.

**Comment by glopesdev** [comment]
Sorry if I wasn't clear. The link to the offending code was provided above:
https://github.com/kahanu/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinq.cs#L1445

If you open the link, it should open the GitHub code browser automatically positioned at line 1445, where the redundant check is.

This for me is the most pressing of these last 3 issues to be fixed, as it poses serious limitations to the use of `DynamicExpression` with no clear gain. I will try to submit the other pull requests soon.
