### ISSUE TITLE
.net Core support

### ISSUE THREAD

**Issue by xrkolovos** [kahanu/System.Linq.Dynamic#49]
any thoughts for .net core support?

**Comment by ryanvgates** [comment]
I would have to take a look and see if there are any conflicts. In principal, I think we should support as many possible frameworks as we can. I know that you can do this relatively simply with the new xproject in VS 2015. 

@kahanu what do you think about adding .net core support this way? To be clear the nuget package produced would support multiple frameworks (e.g. 2.0, 3.0, 3.5, 4.0, 4.5 and core 1).

**Comment by kahanu** [comment]
That would be great if its a new branch.

King

Sent from my Windows Phone
________________________________

**Comment by ryanvgates** [comment]
@kahanu rather than using a separate branch I would like to see if I can do something similar to what is described [here](http://weblog.west-wind.com/posts/2014/Dec/02/Creating-multitarget-NuGet-Packages-with-vNext), which uses a single codebase to produce a nuget package that targets different .net versions. This way we wouldn't have to worry about making the same bug fixes/enhancements across branches.

**Comment by StefH** [comment]
Hi All.

I've started a new project based on this + https://github.com/NArnott/System.Linq.Dynamic to implement **.net core** support.

See this github here: https://github.com/StefH/System.Linq.Dynamic.Core

Please comment / review and help testing.

**Comment by ryanvgates** [comment]
@StefH I will take a look to see how you implemented the .net core support.

Regarding combining all projects/branches into this one, it will take some time to do this since your repository is not a fork off of either of the existing two repositories. I know that https://github.com/NArnott/System.Linq.Dynamic is both ahead and behind this repository as well.

**Comment by StefH** [comment]
Hello @ryanvgates, I forked from https://github.com/NArnott/System.Linq.Dynamic and added some more functionality there.<br>My fork is still visible on github [https://github.com/StefH/System.Linq.Dynamic], however I decided to start a new project + nuget to avoid confusion and create the project according to the new VS2015 + DNXCore/vNext standards.

However, currently there are multiple nuget packages available:

- https://www.nuget.org/packages/System.Linq.Dynamic/ (@kahanu)
- https://www.nuget.org/packages/System.Linq.Dynamic.3.5/ (@kavun : only 3.5 and VB.NET)
- https://www.nuget.org/packages/System.Linq.Dynamic.Library/ (@NArnott)
- https://www.nuget.org/packages/System.Linq.Dynamic.Core/ (@stefh)

So some investigation is needed to compare functionality from all these projects and mine.

An idea would be to analyse all the issues reported on these projects, and add unit-tests in my project to see if these issues are fixed or still need a fix.

**Comment by StefH** [comment]
I did some cross checking from the issues between the different versions, and I think I have integrated most if the new functionality and bugfixes into my repository. If someone has the time, I would really appreciate if you can double check and verify my code and closed/open issues.

**Comment by ryanvgates** [comment]
@StefH I apologize for the delay. I've just started a new job and have some other things going on right now. I will look into comparing the functionality and bugfixes.

**Comment by xrkolovos** [comment]
rc2 is out! :)

**Comment by StefH** [comment]
Yes I know.
I did already port my projects to RC2:

- https://github.com/StefH/Linq.PropertyTranslator.Core
- https://github.com/StefH/QueryInterceptor.Core
- https://github.com/StefH/System.Linq.Dynamic.Core

Please test and double check my **System.Linq.Dynamic.Core** project. (NuGet version 1.0.2 is also uploaded)

**Comment by xrkolovos** [comment]
nice i will check them, when i will upgrade my projects!

**Comment by xrkolovos** [comment]
we are going with the System.Linq.Dynamic.Core packages? (there working fine as far as tested)

**Comment by ryanvgates** [comment]
To anyone that visits this issue, I suggest using [System.Linq.Dynamic.Core](https://github.com/StefH/System.Linq.Dynamic.Core), which @StefH seems to be actively maintaining.
