### ISSUE TITLE
New query / Alias on every orderBy

### ISSUE THREAD

**Issue by andmattia** [kahanu/System.Linq.Dynamic#52]
Hi all

I investigate on a performance issue on my db (mySql) and I see that every orderBy I give me back a new query with new alias. Is it possibile use same alias on every run?

mat

**Comment by ryanvgates** [comment]
Can you please provide an example (with code)? This way I can reproduce the issue and understand what you're running into.

**Comment by ryanvgates** [comment]
Closing this issue since it's been over a month with no response.
