### ISSUE TITLE
SqlFunctions in where clause

### ISSUE THREAD

**Issue by ehsaanwelcome** [kahanu/System.Linq.Dynamic#53]
from
query.Where(o => SqlFunctions.StringConvert((double)product.Id).Contains(search))
to
query.where("SqlFunctions.StringConvert((double)Id.Contains(@0), search)

**Comment by ryanvgates** [comment]
Can you please provide more detail about what this issue is? Is it a bug or enhancement?

How can I reproduce the issue? Can you please reference the place in the code where this is from?

**Comment by StefH** [comment]
I also tried to test this using unit-tests (https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/SqlFunctionsTests.cs) however, I'm not able to test this correctly because my unit-test database is not (yet) a sql-server, but only Sqlite.
Maybe I can quickly try to add this test to a console-app.

**Comment by ehsaanwelcome** [comment]
Is dnt know, is this a bug or enhancement as i am very new to this libraray. 
There are entity functions which are for every database provider and swl functioms which are for sql server. 
in sql, we can cast int to string and many other common functions which is not possible in linw to entities queries so here comes swl functions to support these functions as one i have mentioned stringconbert which is casting long to string same as cast in sql

**Comment by ryanvgates** [comment]
Can you please provide a small sample of code that reproduces the issue?

**Comment by ehsaanwelcome** [comment]
i have following linq query in my project
_db.Products.Where(o => SqlFunctions.StringConvert((double)o.Id).Contains(search));
Id is long which is not searchable but in sql we can cast long to string so EF have given us a way to cast it to string using SqlFunctions.StringConvert((double)o.Id).
i have seen generated sql of above query which is something like 
**select * from products where CAST(Id AS varchar(50)) LIke '%123%'**

now i want to use this using dynamic linq
_db.Products.where("SqlFunctions.StringConvert((double)Id.Contains(@0), search)

there are a lot of other useful functions as well which are listed in following links
https://msdn.microsoft.com/en-us/library/system.data.objects.sqlclient.sqlfunctions(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.data.objects.entityfunctions(v=vs.110).aspx

you can test this with any sample table which have one long property

**Comment by StefH** [comment]
It should be like (for test see: https://github.com/StefH/System.Linq.Dynamic.Core/tree/master/src-console/System.Linq.Dynamic.Core.ConsoleTestApp.net452)

``` c#
class Program
{
    static void Main(string[] args)
    {
        using (var context = new KendoGridDbContext())
        {
            string search = "2";
            var expected = context.Employees.Where(e => System.Data.Entity.SqlServer.SqlFunctions.StringConvert((double) e.EmployeeNumber).Contains(search)).ToArray();
            foreach (var emp in expected)
            {
                Console.WriteLine($"System.Linq : {emp.Id} - {emp.EmployeeNumber}");
            }

            var test = context.Employees.Where("SqlFunctions.StringConvert(double(it.EmployeeNumber)).Contains(@0)", search).ToArray();
            foreach (var emp in test)
            {
                Console.WriteLine($"DynamicLinq : {emp.Id} - {emp.EmployeeNumber}");
            }
        }
    }
}
```

Note that a cast to **double** is required here because StringConvert has two options; with decimal and double.

**Comment by ehsaanwelcome** [comment]
it does not work in my project and in your sample project
i am getting parse exception error, sqlfunction is not a key in type [entity name]

in sample project, i added system.linq.dynamic though nuget because it was not loading it from src

is there any difference on nuget library and the one is in src of sample project?

**Comment by StefH** [comment]
You probably need nuget system.linq.dynamic.core (my project as referenced above)

**Comment by ehsaanwelcome** [comment]
Thanks
It worked

I was using a fork which documentation was at following link
dynamiclinq.azurewebsites.net/Library

now, that library is removed from everywhere.

**Comment by StefH** [comment]
Indeed, that library (which is not this one) is indeed removed from github and nuget. (I don't know why.)

I suggest you use the **System.Linq.Dynamic.Core**.
Documentation can be found here: https://system-linq-dynamic-core.azurewebsites.net

**Comment by ehsaanwelcome** [comment]
Yes, using it now and everything is working 
I really liked the documentation and tests
Really appreciate the contribution
