### ISSUE TITLE
ParseException:'Operator '>' incompatible with operand types 'Decimal' and 'Double'

### ISSUE THREAD

**Issue by TWhidden** [kahanu/System.Linq.Dynamic#56]
Any chance this is a simple one to answer? I know that there is a precision vs range thing here. 

ParseException:'Operator '>' incompatible with operand types 'Decimal' and 'Double' (at index 18)

Working on a work-around, just curious your thoughts.

In this case, left token is a decimal, right token gets parsed as a double.

![decdoucompare](https://cloud.githubusercontent.com/assets/9921122/16283609/502f6212-3882-11e6-92c6-7cd8146e9319.jpg)

**Comment by StefH** [comment]
Can you please provide example code or a unit-test ?

**Comment by TWhidden** [comment]
Sure can.  


 [TestMethod]
        public void DoubleDecimalCompare()
        {
            var listOfDifferentDecimals = new List<TestContainer>();
            listOfDifferentDecimals.Add(new TestContainer(123423.234M));
            listOfDifferentDecimals.Add(new TestContainer(123423423423.2342M));
            listOfDifferentDecimals.Add(new TestContainer(2342342433423.23423423M));
            listOfDifferentDecimals.Add(new TestContainer(123.234M));
            listOfDifferentDecimals.Add(new TestContainer(100000000000.232423423434M));
            listOfDifferentDecimals.Add(new TestContainer(100.232423423434M));
            double d = 1000.0;
            var results = listOfDifferentDecimals.Where("V > @0", d).ToList();
        }

**Comment by TWhidden** [comment]
If you are thinking about writing a solution for this, you might consider the risks of comparing double and decimal.  Thought, it most likely don't impact a majority of folks, the ranges are different. I was reading on StackOverflow what looks like a simple solution.  http://stackoverflow.com/questions/10612207/to-compare-double-and-decimal-should-i-cast-double-to-decimal-or-decimal-to-doub

Though, I am not quite sure how to add it in just yet so I can create a pull request.

**Comment by StefH** [comment]
Note that in normal Linq, this shows the same error on compile-level.

In my version (https://github.com/StefH/System.Linq.Dynamic.Core) it's possible to cast the Decimal to Double like this:

See https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L28
`var result = list.AsQueryable().Where("double(DecimalValue) > @0", d).ToList();`

or

https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/OperatorTests.cs#L26
`var result = models.Select("Decimal(FloatValue) * DecimalValue").First();`

**Comment by StefH** [comment]
Does this answer your question?

**Comment by TWhidden** [comment]
Well, this is part of a higher level framework (WPF DataGrid filtering controls), where adjusting the string values really doesn't help. I get what you are doing there.  What I think I will do is find a way on my higher level control to have the user input already cast to the corrected type before its sent as a parameter.  I was just hoping there was an easy way to do that from the Dynamic Linq control.  Either way, I think its best to pass in the corrected comparison value since precision is something that is important. No need to gum up the clean dynamic link that many people depend on.

**Comment by StefH** [comment]
OK, clear.
