### ISSUE TITLE
First, FirstOrDefault, Single, SingleOrDefault, Take

### ISSUE THREAD

**Issue by DarthVitalus** [kahanu/System.Linq.Dynamic#58]
Greetings! I want to ask you to add support to the library for IEnumerable methods, that are listed in the title. Would you be so kind to do that? :)
The use case that i need to be done is like:
`DynamicExpression.ParseLambda(new[] { someParam }, resType, "someObject.SomeArrayProperty.FirstOrDefault()");`

Thanks in advance!

**Comment by ryanvgates** [comment]
@DarthVitalus Can you submit a pull request with unit tests for this enhancement?

Unfortunately right now, I nor @kahanu have the bandwidth to make additions to this project.

**Comment by StefH** [comment]
@DarthVitalus can you please checkout my library https://github.com/StefH/System.Linq.Dynamic.Core

I think this functionality is already supported, see this unit-test:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/EntitiesTests.FirstOrDefault.cs#L25

**Comment by DarthVitalus** [comment]
@StefH I've already did! Your package is great! Many thanks for your work!
