### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by lokemoon** [kahanu/System.Linq.Dynamic#59]
Is that possible to release with Strong Name signed?

**Comment by ryanvgates** [comment]
@lokemoon I'll have to take a look at it, as other libraries have done it. Please feel free to submit a pull request as well.

**Comment by StefH** [comment]
Please note that in order you want to really secure your library, the secret key should be stored in a safe place. But if you just want to sign the library, you can just store the key in github, same as I do.

**Comment by ryanvgates** [comment]
@lokemoon did you end up using the [System.Linq.Dynamic.Core](https://github.com/StefH/System.Linq.Dynamic.Core) library or is there still a use case for this library to be strongly signed?

**Comment by igorberdich** [comment]
We want to use  System.Linq.Dynamic (not Core) assembly in our project but we need it with strong name.
Is it official Microsoft dll? Usually Microsoft dlls have strong names.
Are you planning to release it with strong name?

**Comment by StefH** [comment]
What's the reason that you don't want to use theSystem.Linq.Dynamic.Core version?

**Comment by igorberdich** [comment]
We have product that was built long ago and our architecture team not ready to move in that direction yet. All our environments not ready for core including build environment. I am not sure that using core version of assembly won't cause problems.

**Comment by lokemoon** [comment]
Hello, we ended using different approach and directly interact our implementation with ExpressionTree.  There was some misunderstand earlier, we thought System.Linq.Dynamic.Core aren't support on legacy .NET, hence we missed out the chance to tried out System.Linq.Dynamic.Core.

**Comment by StefH** [comment]
Indeed. Because I could not use the same name on nuget and because this author dud not add me 😃, I started a new version which supporys the old .net but also the new .net core / netstandard.

**Comment by ryanvgates** [comment]
Unfortunately I don't have the bandwidth to work on this right now, but I believe that you can [sign already built assemblies](https://stackoverflow.com/q/1379954/299327).
