### ISSUE TITLE
Nuget release?

### ISSUE THREAD

**Issue by Elindalyne** [kahanu/System.Linq.Dynamic#61]
Any chance of a release any time soon? It looks like you pulled in a bunch of stuff in March that hasn't made it to Nuget. While I can obviously build the project myself, I'd prefer to be able to update my projects from the same source.

**Comment by StefH** [comment]
If you can't wait on this NuGet, you can try https://www.nuget.org/packages/System.Linq.Dynamic.Core/

**Comment by ryanvgates** [comment]
@Elindalyne I will work on a nuget release and will update here once its been published.

**Comment by ryanvgates** [comment]
Just uploaded [version 1.0.7 to nuget](https://www.nuget.org/packages/System.Linq.Dynamic/1.0.7)

**Comment by ryanvgates** [comment]
@Elindalyne thank you for calling me out on not publishing to nuget for a while
