### ISSUE TITLE
The list of differences between this version and the original

### ISSUE THREAD

**Issue by omariom** [kahanu/System.Linq.Dynamic#65]
Would be nice to know what was added to the version published in ScottGu's blog.

**Comment by ryanvgates** [comment]
@omariom can you provide a link to the specific article of Scott Gu's blog?

**Comment by omariom** [comment]
https://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library

**Comment by StefH** [comment]
For more different versions, see the table in the readme.md from https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by ryanvgates** [comment]
The only source for this that I'm aware of would be the [commit history for this repo](https://github.com/kahanu/System.Linq.Dynamic/commits/master). I don't know of any other changes.
