### ISSUE TITLE
Tokenizer does not handle escaped quotes in strings

### ISSUE THREAD

**Issue by kallanreed** [kahanu/System.Linq.Dynamic#69]
The parser throws errors when parsing strings like `X = "\"test\""` because the NextToken code in ExpressionParser does not properly handle escaped strings.

See: https://github.com/kahanu/System.Linq.Dynamic/blob/d1cfa48813a81665ded417a94a91a10d28e940d7/Src/System.Linq.Dynamic/DynamicLinq.cs#L2335

The tokenizer needs to keep track of whether or not it is handling an escaped character before exiting the loop.

**Comment by StefH** [comment]
I think the code just works fine.
See also some test here:https://github.com/StefH/System.Linq.Dynamic.Core/blob/10fc9a2ec8677f638210804c0ca636de021e6c9a/src-console/System.Linq.Dynamic.Core.ConsoleTestApp.net40/Program.cs#L134

**Comment by kallanreed** [comment]
That test doesn't contain escaped quotes that the ExpressionParser needs to handle. You need a test like `"X==\"\\\"I am a string with quotes in me\\\"\"`.

**Comment by mbilodeau6** [comment]
I submitted a pull request with a fix just in case anyone else need to support this use case.

**Comment by StefH** [comment]
Thanks.

**Comment by ryanvgates** [comment]
Unfortunately I don't have the bandwidth to fix this right now.
