### ISSUE TITLE
Nuget 1.0.7 Solution Doesn't compile due to sign trouble 

### ISSUE THREAD

**Issue by jupagose** [kahanu/System.Linq.Dynamic#72]
When I try to compile my solution it throws an error indicating **System.Linq.Dynamic  1.0.7**  is not signed. If I downgrade to **1.0.4**  My solution compiles with no problems

**Comment by ryanvgates** [comment]
@jupagose What about the versions in between (1.0.6, 1.0.5)? Do you get the same error?

**Comment by ryanvgates** [comment]
This assembly is not signed at this time. I haven't gotten a response back from @jupagose either.
