### ISSUE TITLE
"Where" dynamic linq query parser should give meaningful error when " is null " is used.

### ISSUE THREAD

**Issue by MNF** [kahanu/System.Linq.Dynamic#73]
The following code
```
var formattableString = "$(ReasonID is null)  "; //ReasonID is a column name
                query = query.Where( formattableString);
```
reports " **')' or operator expected**" error, which is hard to understand. 
Finally I found that standard SQL " is null" is not supported, and acceptable syntax is
`var formattableString = $" (ReasonID == null)"`

It will be good if parser will recognize " is null" pattern and either interpret it correctly or give an appropriate error message.
I've  clarified this behavior in https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions#expression-language.

**Comment by ryanvgates** [comment]
Awesome! Thanks for the contribution @MNF .
