### ISSUE TITLE
Support for FirstOrDefault or Single

### ISSUE THREAD

**Issue by aspnetlabs** [kahanu/System.Linq.Dynamic#75]
Could you please add support for FirstOrDefault or Single

**Comment by StefH** [comment]
Take a look at https://github.com/StefH/System.Linq.Dynamic.Core

- https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs#L337
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs#L1240

**Comment by ryanvgates** [comment]
Unfortunately I don't have bandwidth to add features at this time. I'm closing this for now.
