### ISSUE TITLE
OrderBy with multiple properties with comma does not work

### ISSUE THREAD

**Issue by swapnilslomate** [kahanu/System.Linq.Dynamic#79]
If I pass expression like Category DESC, Name ASC then it does not considers Name sorting at all.

Is anyone facing same issue. I checked same for Linq to Entities as well as Linq to Object.

I and using Version 1.0.7.

**Comment by StefH** [comment]
Can you check the unit tests and code at https://github.com/StefH/System.Linq.Dynamic.Core to see if that project works?

**Comment by ryanvgates** [comment]
I'm going to close this due to a lack of response from @swapnilslomate
