### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dradovic** [kahanu/System.Linq.Dynamic#8]
Would it make sense to somewhere include the "Dynamic Expressions.html" which is included in the original release (http://msdn.microsoft.com/en-US/vstudio/bb894665.aspx)? For example, it could be added to the wiki of this page as a documentation readily available for people who want to use this library.

**Comment by ryanvgates** [comment]
@kahanu if we were to add this information to the wiki for this repo, would it make sense to include the samples in the repo itself?

**Comment by ryanvgates** [comment]
@kahanu can you review the pull request #35 and let me know if it's ready to be merged in?

**Comment by ryanvgates** [comment]
I'm going to close this issue since adding the documentation would leave this one issue open too long. I will break it up into smaller chunks.
