### ISSUE TITLE
Support for .net core 2 and .net standard is missing

### ISSUE THREAD

**Issue by AlenToma** [kahanu/System.Linq.Dynamic#86]
Hi i have needed this library unfortunately nuget package does not support .net core and .net standard.
so i have copied your code and made the necessary changes.
Here have a look at the code changes you may find it usefull
https://github.com/AlenToma/EntityWorker.Core/blob/master/Source/EntityWorker.Core/Helper/DynamicLinq.cs

**Comment by StefH** [comment]
An updated version which supports .net core and .netstandard can be found here:
https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by AlenToma** [comment]
jag but it can not convert string to Expression it missing DynamicExpression.ParseLambda which im intressted in

**Comment by StefH** [comment]
That class is now public again, however you should actually use `DynamicExpressionParser`

**Comment by AlenToma** [comment]
thx
